### ISSUE TITLE
Some typos in the preface

### ISSUE THREAD

**Issue by erocarrera** [betanalpha/quarto_chapters#1]
* "reproductive" https://github.com/betanalpha/quarto_chapters/blob/6b89fa9267d8aff661824081a86b763691ff3d8b/preface/preface.tex#L255
* "limitations measurements" https://github.com/betanalpha/quarto_chapters/blob/6b89fa9267d8aff661824081a86b763691ff3d8b/preface/preface.tex#L326
* "we need be proficient" https://github.com/betanalpha/quarto_chapters/blob/6b89fa9267d8aff661824081a86b763691ff3d8b/preface/preface.tex#L404
* "although that that" https://github.com/betanalpha/quarto_chapters/blob/6b89fa9267d8aff661824081a86b763691ff3d8b/preface/preface.tex#L847
* "assumptions inherit to" https://github.com/betanalpha/quarto_chapters/blob/6b89fa9267d8aff661824081a86b763691ff3d8b/preface/preface.tex#L864

**Comment by betanalpha** [comment]
Thanks!  All resolved in 278c6ce1ed0d5e27504084fdfe2932f254301955.
